---
yamllint:
  image: $CI_TOOLS_REGISTRY/ansible-toolset
  stage: test
  allow_failure: true
  variables:
    PY_COLORS: 1
  script:
    - yamllint .

wiki:
  trigger:
    include: deploy.wiki.gitlab-ci.yml
