---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy
  - migrate
  - cleanup

.docker_login:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD_GITLAB $CI_REGISTRY_GITLAB

.docker_proxy_on:
  before_script:
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$HTTP_PROXY\", \"httpsProxy\": \"$HTTPS_PROXY\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'

.docker-full:
  before_script:
    - !reference [.docker_proxy_on, before_script]
    - !reference [.docker_login, before_script]

.docker_build:
  variables:
    DOCKER_BUILDKIT: 0
    DOCKERFILE: ./Dockerfile
    BUILD_MULTISTAGE: 1
  extends: .docker-full
  stage: build
  image: $CI_TOOLS_REGISTRY/docker
  tags:
    - docker
  script:
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" ] && [ "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - |
      DOCKERFILE_NAME=${DOCKERFILE##*/}
      DOCKERFILE_DIR=${DOCKERFILE%/*}
      if [ -z "$image_postfix" ]; then
          image_postfix="/${DOCKERFILE_NAME%.*}"
          if [ $image_postfix == "/Dockerfile" ] || [ $image_postfix == "/dockerfile" ] ; then
          image_postfix=""
          fi
      fi
    - echo $DOCKERFILE_DIR
    - echo $DOCKERFILE_NAME
    - echo $image_postfix
    - export CI_APP_REGISTRY=$CI_REGISTRY_IMAGE$image_postfix
    - export CI_COMMIT_BEFORE_SHORT_SHA=$(echo $CI_COMMIT_BEFORE_SHA | head -c8)
    - |
      if [ "${BUILD_MULTISTAGE}" == "1"  ] ; then
        image_builder_before="$CI_APP_REGISTRY:$CI_COMMIT_BEFORE_SHORT_SHA-builder"
        image_builder_sha="$CI_APP_REGISTRY:$CI_COMMIT_SHORT_SHA-builder"
        image_builder_ref="$CI_APP_REGISTRY:$CI_COMMIT_REF_SLUG-builder"
        if [[ -z "$CI_COMMIT_TAG" ]]; then
          image_builder_tagged=$image_builder_sha
        else
          image_builder_tagged=$image_builder_ref
        fi
        docker image pull "$image_builder_before" || \
        docker image pull "$image_builder_ref" || \
        true
        docker build \
          --cache-from "$image_builder_before" \
          --cache-from "$image_builder_ref" \
          --target builder \
          --build-arg SSH_KEY="$GITLAB_SSH_KEY" \
          $BUILD_EXTRA_ARGS \
          --tag "$image_builder_tagged" \
          --tag "$image_builder_ref" \
          --file $DOCKERFILE .
          docker push "$image_builder_tagged"
          docker push "$image_builder_ref"
        BUILD_EXTRA_ARGS="$BUILD_EXTRA_ARGS --cache-from \"$image_builder_ref\""
      fi
    - image_before="$CI_APP_REGISTRY:$CI_COMMIT_BEFORE_SHORT_SHA"
    - image_sha="$CI_APP_REGISTRY:$CI_COMMIT_SHORT_SHA"
    - image_ref="$CI_APP_REGISTRY:$CI_COMMIT_REF_SLUG"
    - image_latest="$CI_APP_REGISTRY:latest"
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        image_tagged=$image_sha
      else
        image_tagged=$image_ref
      fi
    - |
      docker build \
        --cache-from "$image_before" \
        --cache-from "$image_ref" \
          --build-arg SSH_KEY="$GITLAB_SSH_KEY" \
        $BUILD_EXTRA_ARGS \
        --tag "$image_tagged" \
        --tag "$image_ref" \
        --file $DOCKERFILE $DOCKERFILE_DIR
    - docker push "$image_tagged"
    - docker push "$image_ref"
    - |
      if [ "$CI_COMMIT_REF_SLUG" = "main" ] || [ "$CI_COMMIT_REF_SLUG" = "master" ] || [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$image_tagged" "$image_latest"
        docker push "$image_latest"
      fi

build:
  extends: .docker_build
