---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy
  - migrate
  - validate
  - cleanup


.chart_release:
  image: $CI_TOOLS_REGISTRY/helm
  stage: build
  allow_failure: true
  tags:
    - docker
  script:
    - helm repo add private ${CI_CHART_REGISTRY}
    - chart_sha="1.0.0-sha$CI_COMMIT_SHORT_SHA"
    - chart_ref="1.0.0-$CI_COMMIT_REF_SLUG"
    - CHART_DIR=".helm/release"
    - helm dependency update $CHART_DIR
    - helm lint $CHART_DIR || true
    - |
      if [[ "$CI_COMMIT_REF_SLUG" != "master" ]] && [[ "$CI_COMMIT_REF_SLUG" != "develop" ]]; then
        CHART_DIR=".helm/preview"
        helm dependency update .helm/preview
        helm lint $CHART_DIR || true
      fi;
    - helm push ${CHART_DIR} --version ${chart_sha} ${CI_CHART_REGISTRY}
    - helm push ${CHART_DIR} --version ${chart_ref} ${CI_CHART_REGISTRY}

chart_release:
  extends: .chart_release
