---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy
  - migrate
  - validate
  - cleanup

.docker_login:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD_GITLAB $CI_REGISTRY_GITLAB

.docker_proxy_on:
  before_script:
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$HTTP_PROXY\", \"httpsProxy\": \"$HTTPS_PROXY\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'

.docker_full:
  before_script:
    - !reference [.docker_proxy_on, before_script]
    - !reference [.docker_login, before_script]

.compose-env:
  script:
    - |
      if [[ -z "$IMAGE" ]]; then
        export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      else
        echo already set IMAGE
      fi
      echo IMAGE=$IMAGE
    - |
      if [[ -z "$COMPOSE_PROJECT_NAME" ]]; then
        if [ "$CI_COMMIT_REF_SLUG" = "main" ] || [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
          export COMPOSE_PROJECT_NAME=$CI_PROJECT_PATH_SLUG
        else
          export COMPOSE_PROJECT_NAME=$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
        fi
      else
        echo already set COMPOSE_PROJECT_NAME
      fi
      echo COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
    - |
      if [[ -z "$COMPOSE_FILE" ]]; then
        if [ "$CI_COMMIT_REF_SLUG" = "main" ] || [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
          export COMPOSE_FILE=docker-compose.prod.yaml
        elif [ "$CI_COMMIT_REF_SLUG" = "develop" ]; then
          export COMPOSE_FILE=docker-compose.stage.yaml
        else
          export COMPOSE_FILE=docker-compose.test.yaml
        fi
      else
        echo already set
      fi
      echo COMPOSE_FILE=$COMPOSE_FILE
    - |
      if [[ -z "$DOCKER_HOSTS" ]]; then
        if [ "$CI_COMMIT_REF_SLUG" = "main" ] || [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
          export DOCKER_HOSTS=$DOCKER_PROD_HOSTS
        elif [ "$CI_COMMIT_REF_SLUG" = "develop" ]; then
          export DOCKER_HOSTS=$DOCKER_TEST_HOSTS
        else
          export DOCKER_HOSTS=$DOCKER_TEST_HOSTS
        fi
      else
        echo already set
      fi
      echo COMPOSE_FILE=$COMPOSE_FILE
    - |
      if [[ -z "$NETWORK" ]]; then
        export NETWORK=$CI_PROJECT_NAMESPACE
      else
        echo already set
      fi
      echo NETWORK=$NETWORK
    - |
      if [[ -z "$DOMAIN" ]]; then
        if [ "$CI_COMMIT_REF_SLUG" = "main" ] || [ "$CI_COMMIT_REF_SLUG" = "master" ] && [ ! -z "$DOMAIN_PROD" ]; then
          export DOMAIN=$DOMAIN_PROD
        elif [ "$CI_COMMIT_REF_SLUG" = "develop" ] && [ ! -z "$DOMAIN_STAGE" ]; then
          export DOMAIN=$DOMAIN_STAGE
        else
          export DOMAIN=$CI_BUILD_REF_SLUG.$CI_PROJECT_NAME.$CI_PROJECT_NAMESPACE.$DEMO_DOMAIN
        fi
      else
        echo already set
      fi
    - echo DOMAIN=$DOMAIN

.compose_deploy:
  image: $CI_TOOLS_REGISTRY/docker-compose
  stage: deploy
  extends: .docker_full
  tags:
    - deploy
  script:
    - !reference [.compose-env, script]
    - |
      for host in $DOCKER_HOSTS;
        do export DOCKER_HOST=$host:2375
        echo deploy to $DOCKER_HOST
        docker network create $NETWORK || true
        docker-compose up -d
      done;
    - export DYNAMIC_ENVIRONMENT_URL="https://$DOMAIN"
    - |
      if [[ $DOMAIN =~ "://" ]];
          then DYNAMIC_ENVIRONMENT_URL="$DOMAIN"
      else
          DYNAMIC_ENVIRONMENT_URL="https://$DOMAIN"
      fi
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
    - echo "DOCKER_HOSTS=$DOCKER_HOSTS" >> deploy.env
    - echo "COMPOSE_FILE=$COMPOSE_FILE" >> deploy.env
    - echo "IMAGE=$IMAGE" >> deploy.env
    - echo "DOMAIN=$DOMAIN" >> deploy.env
    - echo "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME" >> deploy.env
    - echo "NETWORK=$NETWORK" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

deploy_compose:
  extends: .compose_deploy
  environment:
    name: review/compose/$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL
    on_stop: stop_compose
    auto_stop_in: 1 week
    kubernetes:
      namespace: $DOCKER_HOSTS
  rules:
    - if: $CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_REF_NAME != "develop"

stop_compose:
  image: $CI_TOOLS_REGISTRY/docker-compose
  variables:
    GIT_STRATEGY: none
  when: manual
  stage: cleanup
  environment:
    name: review/compose/$CI_COMMIT_REF_SLUG
    action: stop
  artifacts:
    reports:
      dotenv: deploy.env
  allow_failure: true
  script:
    - env
    - |
      for host in $DOCKER_HOSTS;
        do export DOCKER_HOST=$host:2375
        echo $DOCKER_HOST
        docker-compose down
      done;
  rules:
    - if: $CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_REF_NAME != "develop"

deploy_compose_staging:
  extends: .compose_deploy
  environment:
    name: staging/compose
    url: $DYNAMIC_ENVIRONMENT_URL
    kubernetes:
      namespace: $DOCKER_HOSTS
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"

deploy_compose_production:
  extends: .compose_deploy
  environment:
    name: production/compose
    url: $DYNAMIC_ENVIRONMENT_URL
    kubernetes:
      namespace: $DOCKER_HOSTS
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
