---
include:
  - dry/stages.yml

wiki-test:
  image: $CI_TOOLS_REGISTRY/wiki
  stage: test
  allow_failure: true
  script:
    - |
      if [[ ! -e mkdocs.yml ]];
      then echo "mkdocs.yml DIDNT EXISTS";
      cat << EOF >> mkdocs.yml
      site_name: $CI_PROJECT_PATH_SLUG
      site_url: $CI_PAGES_URL
      site_dir: public
      docs_dir: wiki
      theme: material
      nav: []
      EOF
      fi;
    - cat mkdocs.yml | envsubst > mkdocs.tmp.yml
    - mv mkdocs.tmp.yml mkdocs.yml
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  image: $CI_TOOLS_REGISTRY/wiki
  stage: deploy
  allow_failure: true
  script:
    - |
      if [[ ! -e mkdocs.yml ]];
      then echo "mkdocs.yml DIDNT EXISTS";
      cat << EOF >> mkdocs.yml
      site_name: $CI_PROJECT_PATH_SLUG
      site_url: $CI_PAGES_URL
      site_dir: public
      docs_dir: wiki
      theme: material
      nav: []
      EOF
      fi;
    - cat mkdocs.yml | envsubst > mkdocs.tmp.yml
    - mv mkdocs.tmp.yml mkdocs.yml
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - master
