---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy
  - migrate
  - validate
  - cleanup

wiki-test:
  image: $CI_TOOLS_REGISTRY/wiki
  stage: test
  allow_failure: true
  script:
    - envsubst < mkdocs.yml > mkdocs.tmp.yml && mv mkdocs.tmp.yml mkdocs.yml
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  image: $CI_TOOLS_REGISTRY/wiki
  stage: deploy
  allow_failure: true
  script:
    - envsubst < mkdocs.yml > mkdocs.tmp.yml && mv mkdocs.tmp.yml mkdocs.yml
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - master
