.ans-validate:
  image: $CI_TOOLS_REGISTRY/ansible-toolset:latest
  stage: validate
  script:
    - chmod 600 $ANSIBLE_SSH_KEY
    - mkdir -p ~/.ssh
    - cp $ANSIBLE_SSH_KEY ~/.ssh/id_rsa
    - chmod 600 -R ~/.ssh
    - cd ${ANS_ROOT}
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -vvv --syntax-check -i inventory -l $ANS_ENV --vault-password-file $ANSIBLE_VAULT_PASSWORD_FILE --private-key $ANSIBLE_SSH_KEY --user root playbook.yaml
  only:
    changes:
      - ansible/**/*

.ans-plan:
  stage: plan
  image: $CI_TOOLS_REGISTRY/ansible-toolset:latest
  script:
    - chmod 600 $ANSIBLE_SSH_KEY
    - mkdir -p ~/.ssh
    - cp $ANSIBLE_SSH_KEY ~/.ssh/id_rsa
    - chmod 600 -R ~/.ssh
    - cd ${ANS_ROOT}
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook --check --diff -i inventory -l $ANS_ENV --vault-password-file $ANSIBLE_VAULT_PASSWORD_FILE --private-key $ANSIBLE_SSH_KEY --user root playbook.yaml | tee ansible_test.diff
  # variables:
  #   ANSIBLE_STDOUT_CALLBACK: actionable
  artifacts:
    paths:
      - ${ANS_ROOT}/ansible_test.diff
  tags:
    - deploy
  except:
    refs:
      - master
  only:
    changes:
      - ansible/**/*

.ans-roles:
  stage: deploy-ans
  when: manual
  timeout: 3h
  image: $CI_TOOLS_REGISTRY/ansible-toolset:latest
  script:
    - chmod 600 $ANSIBLE_SSH_KEY
    - mkdir -p ~/.ssh
    - cp $ANSIBLE_SSH_KEY ~/.ssh/id_rsa
    - chmod 600 -R ~/.ssh
    - cd ${ANS_ROOT}
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -i inventory -l $ANS_ENV --vault-password-file $ANSIBLE_VAULT_PASSWORD_FILE --private-key $ANSIBLE_SSH_KEY --user root playbook.yaml
  tags:
    - deploy
  only:
    refs:
      - master
    changes:
      - ansible/**/*
