---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy
  - migrate
  - validate
  - cleanup

.lint:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - set -vx
    - $LINT_COMMAND
  rules:
    - if: '$LINT_COMMAND'

lint:
  extends: .lint
