---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy

.docker_login:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD_GITLAB $CI_REGISTRY_GITLAB

.docker_proxy_on:
  before_script:
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$HTTP_PROXY\", \"httpsProxy\": \"$HTTPS_PROXY\", \"noProxy\": \"$NO_PROXY\" } } }" > $HOME/.docker/config.json'

.docker-full:
  before_script:
    - !reference [.docker_proxy_on, before_script]
    - !reference [.docker_login, before_script]

molecule-role-common:
  extends:
    - .docker-full
  image: $CI_TOOLS_REGISTRY/ansible-toolset
  stage: test
  tags:
    - test
  variables:
    PY_COLORS: 1
  script:
    - cp $ANSIBLE_SSH_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - molecule test
