---
stages:
  - check
  - build
  - test
  - analyse
  - release
  - deploy

molecule-role-common:
  extends:
    - .docker-full
  image: $CI_TOOLS_REGISTRY/ansible-toolsets
  stage: test
  tags:
    - test
  variables:
    PY_COLORS: 1
  script:
    - molecule test
