variables:
  REBUILD_MYSQL:
    value: "false"
    description: "If you want rebuild (TAKE A LONG TIME) mysql - set to true🌈"
  DROP_MYSQL:
    value: "false"
    description: "If you want drop mysql - set to true🌈"

rebuild-mysql:
  stage: build
  trigger:
    project: 'infra/mysql'
    strategy: depend
  rules:
    - if: '$REBUILD_MYSQL == "true"'

drop-mysql:
  image: $CI_TOOLS_REGISTRY/docker-compose
  stage: analyse
  allow_failure: true
  script:
    - docker-compose pull mysql || true
    - docker-compose stop mysql
    - docker-compose rm -f mysql
    - docker-compose up -d mysql
  rules:
    - if: '$DROP_MYSQL == "true"'
