variables:
  REBUILD_MYSQL:
    value: "false"
    description: "If you want rebuild (TAKE A LONG TIME) mysql - set to true🌈"
  DROP_MYSQL:
    value: "false"
    description: "If you want drop mysql - set to true🌈"
  MIGRATE_COMMAND: echo Specify MIGRATE_COMMAND!
  MIGRATION_TARGET: specify_MIGRATION_TARGET

rebuild-mysql:
  stage: build
  trigger:
    project: 'infra/mysql'
    strategy: depend
  rules:
    - if: '$REBUILD_MYSQL == "true"'

drop-mysql:
  image: $CI_TOOLS_REGISTRY/docker-compose
  stage: analyse
  allow_failure: true
  script:
    - docker-compose pull mysql || true
    - docker-compose stop mysql
    - docker-compose rm -f mysql
    - docker-compose up -d mysql
    - docker-compose exec -T $MIGRATION_TARGET sh -c "sleep 10 && $MIGRATE_COMMAND"
  rules:
    - if: '$DROP_MYSQL == "true"'
