---
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

include:
  - project: 'ci-cd/templates'
    ref: master
    file: 'build.docker.gitlab-ci.yml'
  - project: 'ci-cd/templates'
    ref: master
    file: 'deploy.helm.gitlab-ci.yml'

wiki:
  trigger:
    include:
      - project: 'ci-cd/templates'
        file: 'deploy.wiki.gitlab-ci.yml'
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $WIKI_ENABLED'

deploy_helm:
  extends: .deploy_helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
      when: never

stop_helm:
  extends: .stop_helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
      when: never
